# Entry point for climate-data processing. Product modules will be added here.
source(file.path("R", "config.R"))
source(file.path("R", "acis-prism.R"))
source(file.path("R", "process-prism.R"))
source(file.path("R", "build-prism-climatology.R"))
source(file.path("R", "prism-percentile-rank.R"))
source(file.path("R", "prism-workflow.R"))
source(file.path("R", "map-reference-layers.R"))
source(file.path("R", "map-product-scales.R"))
source(file.path("R", "map-southwest.R"))
source(file.path("R", "build-current-prism-maps.R"))
source(file.path("R", "build-current-prism-precipitation-maps.R"))
source(file.path("R", "prism-accumulation-cache.R"))
source(file.path("R", "prism-rolling-temperature-percentile.R"))
source(file.path("R", "prism-temperature-threshold-cache.R"))
source(file.path("R", "prism-first-freeze.R"))
source(file.path("R", "prism-last-freeze.R"))
source(file.path("R", "prism-freeze-free-season.R"))
source(file.path("R", "prism-water-year-cache.R"))
source(file.path("R", "prism-dry-spell.R"))
source(file.path("R", "prism-longest-dry-spell.R"))
source(file.path("R", "prism-wet-day-count.R"))
source(file.path("R", "prism-wet-day-intensity.R"))
source(file.path("R", "prism-very-wet-contribution.R"))
source(file.path("R", "build-current-prism-water-year-maps.R"))
source(file.path("R", "prism-water-year-maximum.R"))
source(file.path("R", "build-overview-map.R"))
source(file.path("R", "map-product-site.R"))
source(file.path("R", "refresh-retained-freeze-maps.R"))
source(file.path("R", "update-enabled-prism-maps.R"))
source(file.path("R", "daily-update.R"))

check_swc_packages()
initialize_swc_directories()

swc_update_result <- run_swc_daily_update()
